version: '3.1'
services:
  ranger-admin:
    build: ranger-admin
    ports: 
      - 6080:6080
      - 6182:6182
      - 6083:6083
      - 6183:6183
      - 8886:8886
    depends_on:
      - mysqldb
    links:
      - mysqldb
    #command: ["/bin/sh","-c","/opt/ranger-1.0.0-SNAPSHOT-admin/ranger-docker-start.sh"]
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin99
